accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^home/', views.home, name="home"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
]

team/urls.py
from django.conf.urls import url
from . import views

app_name = 'task'

urlpatterns = [
    url(r'^$', views.task_list, name="list"),
    url(r'^create/$', views.task_create, name="create"),
    url(r'^(?P<slug>[\w-]+)/$', views.task_detail, name="detail"),
]

teamBuilder/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from team import views as task_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^tasks/', include('team.urls')),
    url(r'^about/$', views.about),
    url(r'^$', task_view.task_list, name='home'),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

team/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Task(models.Model):
    title = models.CharField(max_length=400)
    Description = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.PROTECT)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.Description[:100] + '....'

team/forms.py
from django import forms
from . import models


class CreateTask(forms.ModelForm):
    class Meta:
        model = models.Task
        fields = ['title', 'Description', 'slug', 'thumb']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            # return redirect('/accounts/home/')
            return redirect('task:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})


def home(request):
    return render(request, 'accounts/welcome.html')


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log the user in
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:

                return redirect('task:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return render(request, 'accounts/login.html')

team/views.py
from django.shortcuts import render, redirect
from .models import Task
# from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms


def task_list(request):
    tasks = Task.objects.all().order_by('title')
    return render(request, 'team/task_list.html', {'tasks': tasks})


def task_detail(request, slug):
    task = Task.objects.get(slug=slug)
    return render(request, 'team/task_detail.html', {'task': task})


@login_required(login_url="/accounts/login/")
def task_create(request):
    if request.method == 'POST':
        form = forms.CreateTask(request.POST, request.FILES)
        if form.is_valid():
            # save article to db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('task:list')
    else:
        form = forms.CreateTask()
    return render(request, 'team/task_create.html', {'form': form})

teamBuilder/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    # return HttpResponse('homepage')
    return render(request, 'homepage.html')

def about(request):
    # return HttpResponse('about')
    return render(request, 'about.html')

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Log in</h1>
<form class="site-form" action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    {% if request.GET.next %}
    <input type="hidden" name="next" value="{{ request.GET.next }}"/>
    {% endif %}
    {{ form }}
    <input type="submit" value="Login"/>
</form>
<p>Not got an account? <a href="{% url 'accounts:signup' %}">Sign Up</a></p>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Signup</h1>
    <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup">
    </form>
{% endblock %}

accounts/templates/accounts/welcome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<nav>
                <ul>
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                    </li>
                </ul>
</nav>
<h1>HI THERE WELCOME TO THE TEAMBUILDER</h1>



</body>
</html>

team/templates/team/task_create.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="create-Task">
        <h2>Create a Task here</h2>

        <form class="site-form" action="{% url 'task:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
</form>

    </div>
{% endblock %}

team/templates/team/task_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="task-detail">
    <div class="task">
        <img src="{{task.thumb.url}}" />
        <h2>{{task.title}}</h2>
        <h3>Written by {{ task.author.username }}</h3>
        <p>{{task.Description}}</p>
        <p>Task Created On : {{task.date}}</p>
    </div>
</div>
{% endblock %}

team/templates/team/task_list.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Task List</h1>
<div class="tasks">
    {% for task in tasks %}
    <div class="task">
        <h2><a href="{% url 'task:detail' slug=task.slug %}">{{ task.title }}</a></h2>
        <p>{{ task.snippet }}</p>
        <p>Task Created On : {{task.date}}</p>
        <p class="author">added by {{ task.author.username }}</p>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/about.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>About</title>
    </head>
    <body>
        <h1>About Us</h1>
        <p>We like django.</p>
    </body>
</html>

templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Djangonauts</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
<header class="wrapper">
    <h1 style="font-size:30px; " class="text-white"><a href="{% url 'home' %}">Team Builder</a></h1>
    <nav>
        <ul>
            {% if user.is_authenticated %}
            <li>
                <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Logout</button>
                </form>
            </li>
            <li><a href="{% url 'task:create' %}" class="highlight">New Article</a></li>
            {% else %}
            <li><a href="{% url 'accounts:login' %}">Login</a></li>
            <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
            {% endif %}
        </ul>
    </nav>
</header>
<div class="wrapper">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Homepage</title>
    </head>
    <body>
        <h1>This is the homepage</h1>
        <p>Welcome to Djangonauts</p>
    </body>
</html>